service: books

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: europe-west1
  project: q****0 # anonymising project id
  credentials: ~/.gcloud/qltr_keyfile.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  createBook:
    events:
      - http: book/create
    handler: createBook
  httpget:
    events:
      - http: httpget
    handler: httpget
